name: Test-StartupProbe

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:

  test-startup-probee:
    name: Test NiFi Helm Chart Startup Probe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.GITHUB_TOKEN }}          
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add dysnix https://dysnix.github.io/charts/
          helm repo update
          helm dep up
      - name: Install Nifi
        run: helm install nifi . --set sts.startupProbe.enabled=true
      - name: Confirm rollout waits until JettyServer starts
        run: |
          kubectl rollout status --watch statefulset/nifi --timeout=10m
          kubectl logs pod/nifi-0 -c app-log | grep 'JettyServer NiFi has started'
